services:
  # app1:
  #   image: testrun1:latest
  #   container_name: testrun1container
  #   build:
  #     context: ./Frontend
  #     dockerfile: dockerfile
  #   # restart: unless-stopped
  #   ports:
  #     - "8080:8080"
  #   command: ["npm", "run", "dev"]
    # depends_on:
    #   - app2
    #   - mysql
    # run 2 commands in the container
    # command: >
    #   sh -c "npm install && npm run build && npm run serve"
    # command: npm run dev
    # command: echo "Hello from app1"
    # depends_on:
    #   - mongo


  # app2:
  #   image: testrun2:latest
  #   container_name: testrun2container
  #   build:
  #     context: ./Backend
  #     dockerfile: dockerfile
  #   # restart: unless-stopped
  #   ports:
  #     - "8081:8080"
  #   command: ["tail", "-f", "/dev/null"]
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./Database-Mysql/mysql_data:/var/lib/mysql
volumes:
  mysql_data: